#!/usr/bin/env bash
# This script displays "Holberton School" 10 times and says "Hi" during the 9th

COUNTER=0
while [ $COUNTER -lt 10 ]
do
		if [ $COUNTER -eq 9 ]
		then
				echo "Hi"
		fi
		echo "Best School"
		(( COUNTER++ ))
done
