#!/usr/bin/env bash
# File:   0-block_all_incoming_traffic_but
# Author: Alex Orland Arévalo Tribaldos
# email:  <3915@holbertonschool.com>

# Configures a ufw firewall to block all incoming traffic
# except for TCP ports 22, 443 and 80.

# install ufw, support both IPv4 and IPv6, and ensure default values
sudo ufw disable
sudo apt-get -y install ufw
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming

# configure
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw reload
