#!/usr/bin/env bash
# shellcheck disable=SC2154

# File:   0-custom_http_response_header
# Author: Alex Orland Arévalo Tribaldos
# email:  <3915@holbertonschool.com>

# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”
# Include a custom 404 page that contains a string
# Add a custom HTTP header named X-Served-By.
# The value of the HTTP header is the hostname of the running server.

sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/404.html
replace="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
replace2="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
replace3="\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "47i\ $replace3$replace$replace2" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
