#!/usr/bin/env bash
# File:   0-iamsomeoneelse
# Author: Alex Orland Arévalo Tribaldos
# email:  <3915@holbertonschool.com>

# Runs the whoami command |Under the user passed as argument.
sudo -u "$1" whoami
