#!/usr/bin/env bash
# File:   1-run_nginx_as_nginx
# Author: Alex Orland Arévalo Tribaldos
# email:  <3915@holbertonschool.com>

# Fix container given to run as nginx user && listen on all active IPs on port 8080

# update nginx config file with user 'nginx'
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# update nginx file to listen to 8080
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# change ownership and permissions of config file
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

# netstat -lpn shows apache2 is using 8080
pkill apache2
sudo -u nginx service nginx restart
